# Generated by Django 6.0.7 on 2026-08-28 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_number', models.CharField(help_text='Unique transport identification number, e.g. TRN20260001', max_length=30, unique=True, verbose_name='Consignment / LR Number')),
                ('party_name_text', models.CharField(blank=True, help_text='Direct party name if not selecting an existing party', max_length=150, verbose_name='Party Name')),
                ('private_mark', models.CharField(help_text='Crucial private mark on cartons/bales (e.g. ABC-458, SGT-991)', max_length=100, verbose_name='Private Mark')),
                ('sender_name', models.CharField(max_length=150, verbose_name='Sender Name (Consignor)')),
                ('sender_city', models.CharField(default='Surat', max_length=100, verbose_name='Sender City')),
                ('receiver_name', models.CharField(max_length=150, verbose_name='Receiver Name (Consignee)')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='Receiver Contact Number')),
                ('source', models.CharField(default='Surat', max_length=100, verbose_name='Source / Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination Hub / City')),
                ('package_count', models.PositiveIntegerField(default=1, verbose_name='Number of Packages / Bales')),
                ('goods_description', models.CharField(help_text='e.g. Textile Sarees, Yarn spools, Diamond machinery parts', max_length=255, verbose_name='Goods Description')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (kg)')),
                ('vehicle_number_text', models.CharField(blank=True, max_length=30, verbose_name='Vehicle Number (Manual / External)')),
                ('driver_name_text', models.CharField(blank=True, max_length=100, verbose_name='Driver Name')),
                ('driver_contact_text', models.CharField(blank=True, max_length=20, verbose_name='Driver Contact')),
                ('receiving_date', models.DateField(default=django.utils.timezone.now, verbose_name='Receiving Date')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Date')),
                ('status', models.CharField(choices=[('RECEIVED', 'Goods Received'), ('SORTED', 'Sorted & Staged'), ('VEHICLE_ASSIGNED', 'Vehicle Assigned'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=30, verbose_name='Current Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks / Special Handling Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcel / Consignment',
                'verbose_name_plural': 'Parcels / Consignments',
                'ordering': ['-receiving_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Party Name')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact Person')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('gst_number', models.CharField(blank=True, max_length=20, verbose_name='GST Number')),
                ('private_mark', models.CharField(help_text="Standard private identification mark used for this party's parcels (e.g. ABC-458)", max_length=100, verbose_name='Private Mark')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Party / Customer',
                'verbose_name_plural': 'Parties / Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30, unique=True, verbose_name='Vehicle Number')),
                ('vehicle_type', models.CharField(choices=[('HEAVY_TRUCK', 'Heavy Line Truck (Surat Main Line)'), ('TEMPO', 'Local Distribution Tempo'), ('MINI_TRUCK', 'Mini Truck / Pickup'), ('CONTAINER', 'Container Trailer'), ('E_LOADER', 'Electric Mini Loader')], default='TEMPO', max_length=30, verbose_name='Vehicle Type')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('driver_contact', models.CharField(max_length=20, verbose_name='Driver Contact')),
                ('capacity', models.CharField(help_text='e.g. 9.5 Tons / 400 Boxes', max_length=50, verbose_name='Load Capacity')),
                ('current_location', models.CharField(default='Surat Hub', max_length=100, verbose_name='Current Location')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available / Ready'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('UNDER_MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=30, verbose_name='Availability Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle / Tempo',
                'verbose_name_plural': 'Vehicles / Fleet',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='ParcelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Location / Depot')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks / Update Notes')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='transport.parcel', verbose_name='Parcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Parcel Status History',
                'verbose_name_plural': 'Parcel Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='transport.party', verbose_name='Party / Client'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parcels', to='transport.vehicle', verbose_name='Assigned Vehicle'),
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Local Driver Name')),
                ('driver_contact', models.CharField(max_length=20, verbose_name='Driver Phone')),
                ('destination_area', models.CharField(max_length=150, verbose_name='Local Delivery Area / Market')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assignment Date & Time')),
                ('delivery_status', models.CharField(choices=[('ASSIGNED', 'Assigned to Tempo'), ('LOADED', 'Loaded into Tempo'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Delivered to Party'), ('FAILED', 'Delivery Failed / Rescheduled')], default='ASSIGNED', max_length=30, verbose_name='Distribution Status')),
                ('notes', models.TextField(blank=True, verbose_name='Distribution Notes / Gate Pass Info')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='transport.parcel', verbose_name='Consignment / Parcel')),
                ('tempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempo_assignments', to='transport.vehicle', verbose_name='Local Tempo / Vehicle')),
            ],
            options={
                'verbose_name': 'Delivery / Distribution Assignment',
                'verbose_name_plural': 'Delivery / Distribution Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
