# Generated by Django 6.0.7 on 2026-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='destination',
            field=models.CharField(default='Ahmedabad', max_length=100, verbose_name='Destination Hub / City'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(default='Saroli Godown, Surat', max_length=100, verbose_name='Current Location'),
        ),
    ]
